### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by shali3** [mancuniancol/script.pulsar.eztv-mc#5]
Hi, Can you please fix this? It happened on my Android.  Thanks.
```
00:54:08 T:1955364536  NOTICE: [script.pulsar.eztv-mc] http://eztvapi.re/show/tt0944947
00:54:09 T:1955364536  NOTICE: [script.pulsar.eztv-mc] Accepted Keywords: ['720p']
00:54:09 T:1955364536  NOTICE: [script.pulsar.eztv-mc] Blocked Keywords: []
00:54:09 T:1955364536  NOTICE: [script.pulsar.eztv-mc] min Size: 0.0 GB
00:54:09 T:1955364536  NOTICE: [script.pulsar.eztv-mc] max Size: MAX
00:54:09 T:1955364536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pulsar.eztv-mc/main.py", line 48, in <module>
                                                provider.register(search, search_movie, search_episode)
                                              File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.pulsar/resources/site-packages/pulsar/provider.py", line 188, in register
                                                results = tuple(method(payload["search_object"]))
                                              File "/mnt/internal_sd/Android/data/org.xbmc.kodi/files/.kodi/addons/script.pulsar.eztv-mc/main.py", line 32, in search_episode
                                                name = resASCII + ' - ' + items['title'] + ' - ' + episode['title'].encode('utf-8') + ' - ' + 'S%02dE%02d'% (info['season'], info['episode'])
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
                                            -->End of Python script error report<--
```

**Comment by mancuniancol** [comment]
Thanks for your feedback.  I will check it this week.

**Comment by mancuniancol** [comment]
Btw, could you give me more information about your configuration? Which episode are you tried to watch?  Because, I did some test and I cannot reproduce your issue

**Comment by shali3** [comment]
Latest episode of game of thrones

**Comment by shali3** [comment]
The Environment is Android stick 4.4.2 running Kodi 15 beta2

**Comment by mancuniancol** [comment]
Ok, I am testing only in Kodi 14.  But, it is working now with that episode.

**Comment by shali3** [comment]
I'll take another look later today.
Thanks anyway
